### ISSUE TITLE
Can we add password protection on write on NFC tag?

### ISSUE THREAD

**Issue by GauravCreed** [romellfudi/FudiNFC#11]
Hi @romellfudi 

Can we  add password protection on NFC write tag?  i want develop like NFC tag only write from my application, not other application can write on that NFC tag,

yes but read NFC can possible on all other applications.
Thanks(_)

**Comment by romellfudi** [comment]
Yes, it could be possible pass a pin into nfcA by using `tranceive(command)` instead of `writeNdefMessage(message)`

Please see the following page: 
https://stackoverflow.com/q/73222079

**Comment by romellfudi** [comment]
Can you send a pull request with the feature?

**Comment by GauravCreed** [comment]
Hi @romellfudi 

I am the same user which is comment in this [stackoverflow link](https://stackoverflow.com/q/73222079) which you posted,

I already follow your instruction for write data with password security, but unfortunately I lost the Nfc tag, I am not able to write again on this tag, only we can read this tag.

code for write data into tag with set Tag Lock
` byte[] result = ultralight.transceive(new byte[]{
                            (byte)0xA2,  // Command: WRITE
                            (byte)0x02,  // Address: page 0x02 (2)
                            (byte)0x00, (byte)0x00, (byte)0xFF, (byte)0xFF  // Data: set bytes 2-3 to all '1'
                    });`


code for write data into tag with set Tag UnLock
`byte[] result = ultralight.transceive(new byte[]{
                            (byte)0xA2,  // Command: WRITE
                            (byte)0x02,  // Address: page 0x02 (2)
                            (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00
                    });`

am i did right or wrong?
Thanks.

**Comment by romellfudi** [comment]
Please attach the log and video

**Comment by GauravCreed** [comment]
Hi @romellfudi 

[Security code for NFC Write](https://drive.google.com/file/d/1wWx1CjaEg0AzrBeXwGpw6BeuZRGXflqR/view?usp=share_link)

**Comment by romellfudi** [comment]
@GauravCreed I've said your error log

**Comment by romellfudi** [comment]
@GauravCreed I've said your error log

**Comment by GauravCreed** [comment]
**android.nfc.TagLostException: Tag was lost.
     at android.nfc.TransceiveResult.getResponseOrThrow(TransceiveResult.java:48)
     at android.nfc.tech.BasicTagTechnology.transceive(BasicTagTechnology.java:151)
     at android.nfc.tech.MifareUltralight.writePage(MifareUltralight.java:193)
     at com.nfctagsecurity.security.WriteNFCActivity.writeMethodMifareUltralight(WriteNFCActivity.java:89)
     at com.nfctagsecurity.security.WriteNFCActivity.onNewIntent(WriteNFCActivity.java:47)
     at android.app.Activity.performNewIntent(Activity.java:7162)
     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1431)
     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1450)
     at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3232)
     at android.app.ActivityThread.performNewIntents(ActivityThread.java:3248)
     at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3265)
     at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:193)
     at android.app.ActivityThread.main(ActivityThread.java:6863)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)**

**Comment by romellfudi** [comment]
Well it's a wrong command exception :

https://stackoverflow.com/questions/38768310/android-nfcv-transceive-throws-an-exception

**Comment by romellfudi** [comment]
Did you ask to @MichaelsPlayground, what happens when you run the activity created by him when passing your NFC tag

**Comment by MichaelsPlayground** [comment]
@GauravCreed: In my comment to your SO question I kindly asked to modify my activity ("https://github.com/MichaelsPlayground/NfcNfcaAuthProtection/blob/master/app/src/main/java/de/androidcrypto/nfcnfcaauthprotection/SetWriteProtectionActivity.java") to run with a NTAG213 (I don't own one, so I cannot test it).

Have a look at the official datasheet for NTAG 213/215/216 to find out which addresses should have written to write a password protection to your tag.

You are using the "MifareUltralight" class, why don't you use the "NfcA" class directly ?
